import logging

# 日志格式
logging.basicConfig(level=logging.INFO,
                    format='%(asctime)s - %(filename)s[line:%(lineno)d] - %(levelname)s: %(message)s')
log = logging.getLogger('fault_detection')

# 故障等级对应
SEVERITY = {
    'severe': 1,
    'moderate': 2,
    'mild': 3
}

SERVER_HOST_IP = '10.180.20.1'
SERVER_PORT = 32456

LEVEL_SEVERE = 'severe'
LEVEL_MODERATE = 'moderate'
LEVEL_MILD = 'mild'

# 数据库配置
MYSQL_CONFIG = {
    'host': 'localhost',
    'port': 3306,
    'user': 'root',
    'password': '1',
    'charset': 'utf8',
    'use_unicode': True,
    'get_warnings': True,
    'auth_plugin': 'mysql_native_password',
    'database': 'hd_server_second'
}

# 数据库参数
MYSQL_DB_NAME = 'hd_server_second'
MYSQL_FAULT_TABLE_NAME = 'fault'
MYSQL_HISTORY_FAULT_TABLE_NAME = 'history_fault'
MYSQL_TOPO_TABLE_NAME = 'topo'
MYSQL_FORWARD_TABLE_NAME = 'forward'
MYSQL_DEVICE_DETAILS_TABLE_NAME = 'device_details'

# 数据表读取间隔
MYSQL_READ_FAULT_PERIOD = 5
MYSQL_READ_TOPO_PERIOD = 10

# 故障表名称
FAULT_NAME_HARDWARE = 'HW'
FAULT_NAME_TRAFFIC = 'TRAFFIC'
FAULT_NAME_PROTOCOL = 'PROTO'
FAULT_NAME_APPLICATION = 'APP'
FAULT_NAME_INTERFACE = 'IF'

FAULT_CLASS_NAME = 'fault_handler'
FAULT_NAME_TO_CLASS = {
    FAULT_NAME_HARDWARE: 'HardwareFault',
    FAULT_NAME_TRAFFIC: 'TrafficFault',
    FAULT_NAME_PROTOCOL: 'ProtocolFault',
    FAULT_NAME_APPLICATION: 'ApplicationFault',
    FAULT_NAME_INTERFACE: 'InterfaceFault'
}

# 故障名
# 流量故障名称
FAULT_TRAFFIC_BLACK_HOLE = 'TRAFFIC_BLK_HOLE'
FAULT_TRAFFIC_PACKET_LOSS = 'TRAFFIC_PKT_LOSS'
FAULT_TRAFFIC_PORT_SCAN = 'TRAFFIC_PT_SCAN'
FAULT_TRAFFIC_LOAD_BURST = 'TRAFFIC_LOAD_BURST'
FAULT_TRAFFIC_BROADCAST_STORM = 'TRAFFIC_BROADCAST_STORM'
FAULT_TRAFFIC_STP_CIRCLE = 'TRAFFIC_STP_CIRCLE'

# 硬件故障名称
FAULT_HARDWARE_DEVICE_OFFLINE = 'HW_DEVICE_OFFLINE'
FAULT_HARDWARE_CONFIGURATION_ERROR = 'HW_CONF_ERR'
FAULT_HARDWARE_CPU_HIGH = 'HW_CPU_HIGH'
FAULT_HARDWARE_MEM_HIGH = 'HW_MEM_HIGH'
FAULT_HARDWARE_DISK_HIGH = 'HW_DISK_HIGH'
FAULT_HARDWARE_LINK_ERROR = 'HW_LINK_ERR'
FAULT_HARDWARE_LINK_DOWN = 'HW_LINK_DOWN'

# 协议故障名称
FAULT_PROTO_STP_STATUS_ERROR = 'PROTO_STP_STATUS_ERR'
FAULT_PROTO_MAC_ERROR = 'PROTO_MAC_ERR'
FAULT_PROTO_ARP_ERROR = 'PROTO_ARP_ERR'

# 应用故障名称
FAULT_APPLICATION_CONNECTION_ERROR = 'APP_CONNEC_ERR'
FAULT_APPLICATION_CONNECTION_TIMEOUT = 'APP_CONNEC_TIMEOUT'

# 接口故障名称
FAULT_INTERFACE_CONNECTION_ERROR = 'IF_CONNEC_ERR'
FAULT_INTERFACE_CONNECTION_TIMEOUT = 'IF_CONNEC_TIMEOUT'
FAULT_INTERFACE_STATUS_CODE_ERROR = 'IF_STATUS_CODE_ERR'

# 故障对应中文名
FAULT_DESC_TABLE = {
    FAULT_HARDWARE_DEVICE_OFFLINE: '设备掉线',
    FAULT_HARDWARE_LINK_DOWN: '链路中断',
    FAULT_HARDWARE_LINK_ERROR: '硬件链路故障',
    FAULT_HARDWARE_MEM_HIGH: '内存高占用',
    FAULT_HARDWARE_DISK_HIGH: '硬盘高占用',
    FAULT_HARDWARE_CONFIGURATION_ERROR: '硬件配置信息无法获取',
    FAULT_HARDWARE_CPU_HIGH: 'CPU高占用',

    FAULT_TRAFFIC_BLACK_HOLE: '路由黑洞',
    FAULT_TRAFFIC_PORT_SCAN: '端口扫描',
    FAULT_TRAFFIC_LOAD_BURST: '链路负载激增',
    FAULT_TRAFFIC_PACKET_LOSS: '大量丢包',
    FAULT_TRAFFIC_STP_CIRCLE: '转发环路',
    FAULT_TRAFFIC_BROADCAST_STORM: '广播风暴',

    FAULT_PROTO_MAC_ERROR: 'MAC表计算错误',
    FAULT_PROTO_STP_STATUS_ERROR: 'STP端口状态计算错误',
    FAULT_PROTO_ARP_ERROR: 'APR表计算错误',

    FAULT_APPLICATION_CONNECTION_TIMEOUT: '应用连接超时',
    FAULT_APPLICATION_CONNECTION_ERROR: '应用连接错误',

    FAULT_INTERFACE_CONNECTION_ERROR: '接口连接错误',
    FAULT_INTERFACE_STATUS_CODE_ERROR: '接口状态码错误',
    FAULT_INTERFACE_CONNECTION_TIMEOUT: '接口连接超时'
}